# Data Pre-Processing

## Importing Libraries

In [4]:
import pandas as pd
import numpy as np

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
df=pd.read_csv("freshers_final cleaned_63check.csv")

In [7]:
df

,job_title,Experience,Company,Salary,Location
0,Software Developer / Engineer Jobs Opening in ...,0 Years,Rayapuri Media OPC Pvt Ltd,20000 - 40000 Monthly,Hyderabad
1,Python Junior Software Engineer Web Scraping A...,0 to 1 Years,Insytelli services,25000 - 35000 Monthly,Bangalore
2,WordPress Development Jobs Opening in Stirring...,0 Years,Stirring Minds,Salary not disclosed,Delhi
3,Web Development Jobs Opening in Stirring Minds...,0 Years,Stirring Minds,Salary not disclosed,Delhi
4,Full Stack Development Jobs Opening in Stirrin...,0 Years,Stirring Minds,Salary not disclosed,Delhi
...,...,...,...,...,...
1255,Front End Developer Jobs Opening in Cassius Te...,0 Years,Cassius Technologies,55000 - 75000 Monthly,Asansol
1256,Front End Developer Jobs Opening in Cassius Te...,0 Years,Cassius Technologies,55000 - 75000 Monthly,Nizamabad
1257,Web Developer Jobs Opening in Client of Freshe...,0 Years,Client of Freshersworld,50000 - 75000 Monthly,Kollam
1258,Web Developer Jobs Opening in Client of Freshe...,0 Years,Client of Freshersworld,50000 - 75000 Monthly,Kochi
1259,Web Developer Jobs Opening in Client of Freshe...,0 Years,Client of Freshersworld,50000 - 75000 Monthly,Wayanad

## Checking Null value

In [9]:
df.isnull().sum()

job_title      2
Experience     2
Company        2
Salary         2
Location      47
dtype: int64

## Removing the common null value in all columns

In [11]:
df=df.dropna(how="all")

In [12]:
df.isna().sum()

job_title      0
Experience     0
Company        0
Salary         0
Location      45
dtype: int64

## Checking duplicates

In [14]:
df.duplicated().sum()

17

## Remove duplicates

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.duplicated().sum()

0

In [18]:
df['job_title'].unique()

array(['Software Developer / Engineer Jobs Opening in Rayapuri Media OPC Pvt Ltd at Panjagutta, Hyderabad',
       'Python Junior Software Engineer Web Scraping And Automation Entry Level Jobs Opening in Insytelli services at Sahakara Nagar, Bangalore',
       'WordPress Development Jobs Opening in Stirring Minds at Delhi',
       ...,
       'Web Developer Jobs Opening in Client of Freshersworld at Kollam',
       'Web Developer Jobs Opening in Client of Freshersworld at Kochi',
       'Web Developer Jobs Opening in Client of Freshersworld at Wayanad'],
      dtype=object)

In [19]:
df['Experience'].unique()

array(['0 Years', '0 to 1 Years', '2.5 to 3+ Years', '0 to 3+ Years',
       '3+ Years', '2 to 3+ Years', '3 to 3+ Years', '1 to 3+ Years',
       '1 to 2 Years', '1 to 2.5 Years', '1.5 Years', '1 Years',
       '1.5 to 3+ Years', '0 to 3 Years', '0.6 to 3+ Years',
       '0 to 2 Years', '2 Years', '1 to 3 Years', '0.6 to 3 Years',
       '0.6 Years', '0.6 to 2 Years', '2 to 3 Years', '0.6 to 1 Years',
       '0 to 0.6 Years'], dtype=object)

#### Replacing specific ranges of experience with standardized values

In [21]:
df['Experience'] = df['Experience'].str.replace('0 Years', '0')
df['Experience'] = df['Experience'].str.replace('0 to 1 Years', '1')
df['Experience'] = df['Experience'].str.replace('0 to 3+ Years', '3')
df['Experience'] = df['Experience'].str.replace('2 to 3+ Years', '3')
df['Experience'] = df['Experience'].str.replace('3 to 3+ Years', '4')
df['Experience'] = df['Experience'].str.replace('1 to 3+ Years', '2')
df['Experience'] = df['Experience'].str.replace('1 to 2 Years', '1')
df['Experience'] = df['Experience'].str.replace('1 to 2.5 Years', '2')
df['Experience'] = df['Experience'].str.replace('2.5 to 3+ Years', '3')
df['Experience'] = df['Experience'].str.replace('1.5 Years', '1')
df['Experience'] = df['Experience'].str.replace('1 Years', '1')
df['Experience'] = df['Experience'].str.replace('1.5 to 3+ Years', '2')
df['Experience'] = df['Experience'].str.replace('0.6 to 3+ Years', '2')
df['Experience'] = df['Experience'].str.replace('0 to 3 Years', '2')
df['Experience'] = df['Experience'].str.replace('0 to 2 Years', '1')
df['Experience'] = df['Experience'].str.replace('2 Years', '2')
df['Experience'] = df['Experience'].str.replace('1 to 3 Years', '2')
df['Experience'] = df['Experience'].str.replace('0.6 to 3 Years', '1')
df['Experience'] = df['Experience'].str.replace('0.6 Years', '0')
df['Experience'] = df['Experience'].str.replace('0.6 to 2 Years', '1')
df['Experience'] = df['Experience'].str.replace('2 to 3 Years', '3')
df['Experience'] = df['Experience'].str.replace('0.6 to 1 Years', '1')
df['Experience'] = df['Experience'].str.replace('0 to 0.6 Years', '0')
df['Experience'] = df['Experience'].str.replace('0.6 to 2', '1')
df['Experience'] = df['Experience'].str.replace('3+ Years', '4')
df['Experience'] = df['Experience'].str.replace('0.6 to 1', '1')
df['Experience'] = df['Experience'].str.replace('0 to 0', '0')

In [22]:
df['Experience'].unique()

array(['0', '1', '3', '4', '2'], dtype=object)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1241 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   job_title   1241 non-null   object
 1   Experience  1241 non-null   object
 2   Company     1241 non-null   object
 3   Salary      1241 non-null   object
 4   Location    1196 non-null   object
dtypes: object(5)
memory usage: 58.2+ KB

### Coverting the datatype

In [25]:
df['Experience']=df['Experience'].astype("int64")

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1241 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   job_title   1241 non-null   object
 1   Experience  1241 non-null   int64
 2   Company     1241 non-null   object
 3   Salary      1241 non-null   object
 4   Location    1196 non-null   object
dtypes: int64(1), object(4)
memory usage: 58.2+ KB

In [27]:
df['Salary'].value_counts()

Salary
25000 - 50000 Monthly    386
Salary not disclosed     210
56000 - 76000 Monthly    200
55000 - 75000 Monthly    197
45000 - 65000 Monthly     99
                        ...
20000 - 26000 Monthly      1
3000 Monthly               1
40000 Monthly              1
11111 Monthly              1
12000 - 35000 Monthly      1
Name: count, Length: 89, dtype: int64

In [28]:
df['Salary']=df['Salary'].replace("Salary not disclosed",np.nan)

In [29]:
df.head(5)

,job_title,Experience,Company,Salary,Location
0,Software Developer / Engineer Jobs Opening in ...,0,Rayapuri Media OPC Pvt Ltd,20000 - 40000 Monthly,Hyderabad
1,Python Junior Software Engineer Web Scraping A...,1,Insytelli services,25000 - 35000 Monthly,Bangalore
2,WordPress Development Jobs Opening in Stirring...,0,Stirring Minds,NaN,Delhi
3,Web Development Jobs Opening in Stirring Minds...,0,Stirring Minds,NaN,Delhi
4,Full Stack Development Jobs Opening in Stirrin...,0,Stirring Minds,NaN,Delhi

In [30]:
df['Salary'].isnull().sum()

210

In [31]:
df['Salary'].unique()

array(['20000 - 40000 Monthly', '25000 - 35000 Monthly', nan,
       '10000 - 15000 Monthly', '2500 - 4000 Monthly',
       '12000 - 20000 Monthly', '18000 Monthly', '15000 Monthly',
       '5000 - 10000 Monthly', '10000 - 12000 Monthly', '5000 Monthly',
       '25000 - 40000 Monthly', '45000 - 100000 Monthly',
       '7000 - 20000 Monthly', '15000 - 20000 Monthly',
       '15000 - 16000 Monthly', '20000 - 25000 Monthly',
       '25000 - 30000 Monthly', '30000 - 35000 Monthly',
       '20000 - 50000 Monthly', '30000 - 40000 Monthly',
       '5000 - 15000 Monthly', '29000 - 47000 Monthly',
       '2000000 - 3200000 Yearly', '13000 - 15000 Monthly',
       '15000 - 25000 Monthly', '10000 Monthly', '22000 - 23000 Monthly',
       '20000 - 30000 Monthly', '2000 - 40000 Monthly',
       '100000 - 125000 Monthly', '15000 - 18000 Monthly',
       '2000 - 3000 Monthly', '5000 - 8000 Monthly',
       '50000 - 70000 Monthly', '6000 - 12000 Monthly',
       '40000 - 80000 Monthly', '8000 Monthly', '30000 - 70000 Monthly',
       '25000 - 37500 Monthly', '16000 - 22000 Monthly',
       '400000 - 600000 Yearly', '4000 - 6000 Monthly',
       '20000 - 43000 Monthly', '12000 - 35000 Monthly', '35000 Monthly',
       '8000 - 20000 Monthly', '20000 - 26000 Monthly', '3000 Monthly',
       '40000 Monthly', '15000 - 30000 Monthly', '15000 - 50000 Monthly',
       '11111 Monthly', '5000 - 7500 Monthly', '2000 - 15000 Monthly',
       '30000 - 50000 Monthly', '300000 - 350000 Monthly',
       '170000 - 200000 Monthly', '180000 - 300000 Monthly',
       '50000 - 60000 Monthly', '12000 - 15000 Monthly',
       '58000 - 60000 Monthly', '1000000 - 3000000 Yearly',
       '300000 Yearly', '50000 - 250000 Monthly', '18000 - 30000 Monthly',
       '25000 - 29000 Monthly', '8000 - 15000 Monthly',
       '50000 - 58333 Monthly', '3000 - 5000 Monthly',
       '28000 - 47000 Monthly', '38000 - 52000 Monthly',
       '150000 - 200000 Yearly', '20000 - 60000 Monthly',
       '12000 - 30000 Monthly', '16000 - 30000 Monthly',
       '12000 - 16000 Monthly', '25000 - 50000 Monthly',
       '15000 - 35000 Monthly', '32000 - 47000 Monthly',
       '50000 - 90000 Monthly', '24000 - 38000 Monthly',
       '4000 - 5000 Monthly', '29000 - 48000 Monthly',
       '45000 - 65000 Monthly', '56000 - 76000 Monthly',
       '55000 - 75000 Monthly', '68000 - 74000 Monthly',
       '50000 - 75000 Monthly'], dtype=object)

### Extracting the yearly data only

In [33]:
df[df['Salary'].str.contains("Yearly",na=False)]

,job_title,Experience,Company,Salary,Location
124,SFDC Tester Jobs Opening in Vy systems at Asho...,4,Vy systems,2000000 - 3200000 Yearly,Hyderabad
210,Senior WordPress Developer Jobs Opening in CXO...,0,CXO Enterprises Private Limited,400000 - 600000 Yearly,Bangalore
297,Sr. Python / Lead Engineer - REMOTE Jobs Openi...,4,Anvayainfosolutions,1000000 - 3000000 Yearly,Bangalore
301,Software Trainee Engineer Jobs Opening in Tale...,0,TalentBridge Technologies Pvt Ltd,300000 Yearly,Bangalore
302,Software Engineer Trainee Jobs Opening in Tale...,0,TalentBridge Technologies Pvt Ltd,300000 Yearly,Bangalore
332,Junior Salesforce Developer Jobs Opening in To...,0,Torrance Consultancy,150000 - 200000 Yearly,Hyderabad

### Replace the yearly data to monthly

In [35]:
df['Salary'] = df['Salary'].str.replace('2000000 - 3200000 Yearly','170000 - 270000 Monthly')
df['Salary'] = df['Salary'].str.replace('400000 - 600000 Yearly','34000 - 50000 Monthly')
df['Salary'] = df['Salary'].str.replace('1000000 - 3000000 Yearly','83000 - 250000 Monthly')
df['Salary'] = df['Salary'].str.replace('300000 Yearly','25000 Monthly')
df['Salary'] = df['Salary'].str.replace('150000 - 200000 Yearly','12500 - 17000 Monthly')

In [36]:
df['Salary'].str.contains("Yearly").sum()

0

In [37]:
df['Salary'].unique()

array(['20000 - 40000 Monthly', '25000 - 35000 Monthly', nan,
       '10000 - 15000 Monthly', '2500 - 4000 Monthly',
       '12000 - 20000 Monthly', '18000 Monthly', '15000 Monthly',
       '5000 - 10000 Monthly', '10000 - 12000 Monthly', '5000 Monthly',
       '25000 - 40000 Monthly', '45000 - 100000 Monthly',
       '7000 - 20000 Monthly', '15000 - 20000 Monthly',
       '15000 - 16000 Monthly', '20000 - 25000 Monthly',
       '25000 - 30000 Monthly', '30000 - 35000 Monthly',
       '20000 - 50000 Monthly', '30000 - 40000 Monthly',
       '5000 - 15000 Monthly', '29000 - 47000 Monthly',
       '170000 - 270000 Monthly', '13000 - 15000 Monthly',
       '15000 - 25000 Monthly', '10000 Monthly', '22000 - 23000 Monthly',
       '20000 - 30000 Monthly', '2000 - 40000 Monthly',
       '100000 - 125000 Monthly', '15000 - 18000 Monthly',
       '2000 - 3000 Monthly', '5000 - 8000 Monthly',
       '50000 - 70000 Monthly', '6000 - 12000 Monthly',
       '40000 - 80000 Monthly', '8000 Monthly', '30000 - 70000 Monthly',
       '25000 - 37500 Monthly', '16000 - 22000 Monthly',
       '34000 - 50000 Monthly', '4000 - 6000 Monthly',
       '20000 - 43000 Monthly', '12000 - 35000 Monthly', '35000 Monthly',
       '8000 - 20000 Monthly', '20000 - 26000 Monthly', '3000 Monthly',
       '40000 Monthly', '15000 - 30000 Monthly', '15000 - 50000 Monthly',
       '11111 Monthly', '5000 - 7500 Monthly', '2000 - 15000 Monthly',
       '30000 - 50000 Monthly', '300000 - 350000 Monthly',
       '170000 - 200000 Monthly', '180000 - 300000 Monthly',
       '50000 - 60000 Monthly', '12000 - 15000 Monthly',
       '58000 - 60000 Monthly', '83000 - 250000 Monthly', '25000 Monthly',
       '50000 - 250000 Monthly', '18000 - 30000 Monthly',
       '25000 - 29000 Monthly', '8000 - 15000 Monthly',
       '50000 - 58333 Monthly', '3000 - 5000 Monthly',
       '28000 - 47000 Monthly', '38000 - 52000 Monthly',
       '12500 - 17000 Monthly', '20000 - 60000 Monthly',
       '12000 - 30000 Monthly', '16000 - 30000 Monthly',
       '12000 - 16000 Monthly', '25000 - 50000 Monthly',
       '15000 - 35000 Monthly', '32000 - 47000 Monthly',
       '50000 - 90000 Monthly', '24000 - 38000 Monthly',
       '4000 - 5000 Monthly', '29000 - 48000 Monthly',
       '45000 - 65000 Monthly', '56000 - 76000 Monthly',
       '55000 - 75000 Monthly', '68000 - 74000 Monthly',
       '50000 - 75000 Monthly'], dtype=object)

In [38]:
df['Salary']=df['Salary'].str.replace("Monthly","")

In [39]:
df['Salary']

0       20000 - 40000
1       25000 - 35000
2                  NaN
3                  NaN
4                  NaN
             ...
1254    55000 - 75000
1255    55000 - 75000
1257    50000 - 75000
1258    50000 - 75000
1259    50000 - 75000
Name: Salary, Length: 1241, dtype: object

In [40]:
df['job_title'].value_counts()

job_title
Python Developer Jobs Opening in ADITHYA IT SOLUTIONS PRIVATE LTD at Salem               2
Network Engineer Jobs Opening in SMART ENTRY IT INFRASTRUCTURE at Anna Nagar, Chennai    2
Java Developer Jobs Opening in Client of Freshersworld at Tirupati                       1
Java Developer Jobs Opening in Client of Freshersworld at Wardha                         1
Java Developer Jobs Opening in Client of Freshersworld at Port Blair                     1
                                                                                        ..
Automation Test Engineer Jobs Opening in A Client of Freshersworld at Silchar            1
Automation Test Engineer Jobs Opening in A Client of Freshersworld at Jorhat             1
Automation Test Engineer Jobs Opening in A Client of Freshersworld at Baksa              1
Automation Test Engineer Jobs Opening in A Client of Freshersworld at Bishwanath         1
Web Developer Jobs Opening in Client of Freshersworld at Wayanad                         1
Name: count, Length: 1239, dtype: int64

In [41]:
df["job_title"]=df["job_title"].str.split("Jobs").str[0]

In [42]:
df['job_title'] = df['job_title'].replace('Beginning Your Career With Dot Net Developer ', 'Dot Net Developer')
df['job_title'] = df['job_title'].replace('Start Your Career With Frontend Developer ', 'Frontend Developer')
df['job_title'] = df['job_title'].replace('Start Your Career With Software Testing Internship/ Training ', 'Software Testing Internship/ Training')
df['job_title'] = df['job_title'].replace('Walk-In For System Operator ', 'System Operator')
df['job_title'] = df['job_title'].replace('Immediate Walkin Drive For Software Tester In Salem ', 'Software Tester')
df['job_title'] = df['job_title'].replace('We Are Hiring For IMS ', 'IMS')
df['job_title'] = df['job_title'].replace('We Are Hiring Data Analyst In Salem ', 'Data Analyst')
df['job_title'] = df['job_title'].replace('We Are Hiring For IMS ', 'IMS')
df['job_title'] = df['job_title'].replace('Beginning Your Career With Dot Net Developer ', 'DotÂ NetÂ Developer')

In [43]:
df['job_title'] = df['job_title'].replace('System Administrator In Salem ', 'System Administrator')
df['job_title'] = df['job_title'].replace('System Operator In Salem ', 'System Operator')
df['job_title'] = df['job_title'].replace('Urgent Required Java Intern Fresher ', 'Java Intern')
df['job_title'] = df['job_title'].replace('.NET Developer - 1 Year Experience ', 'Dot Net Developer')
df['job_title'] = df['job_title'].replace('HE pvt ltd Raipur Remote Work From Home Recruitment 2024 | Apply Online', 'HE Remote Work')
df['job_title'] = df['job_title'].replace('We Are Hiring For IMS Role At Salem ', 'IMS')
df['job_title'] = df['job_title'].replace('.NET Developer ', 'Dot Net Developer')

In [44]:
df['job_title'].unique()

array(['Software Developer / Engineer ',
       'Python Junior Software Engineer Web Scraping And Automation Entry Level ',
       'WordPress Development ', 'Web Development ',
       'Full Stack Development ', 'Blockchain Development ',
       'Mobile App Development ', 'Artificial Intelligence - AI ',
       'Asp.net Development ', 'Big Data ', 'Software Development ',
       'Game Development ', 'Product Management ', 'Data Science ',
       'Cloud Computing Intern ', '3D Unity Development ',
       'Systems Development Engineer ', 'Front End Development ',
       'Flutter Development ', 'Android App Development ',
       'Laravel Development Intern ', 'Flutter Developer Intern ',
       '.NET Development ', 'Reactjs Development ',
       'AWS DevOps Engineer ', 'PHP And Laravel Developers ',
       'Python Development ', 'Embedded Systems ', 'QA Testing ',
       'SAP HANA (S/4) Consulting ', 'PHP Development ',
       'Large Language Model Researcher ', 'Data Analytics ',
       'JavaScript Developer ', 'System & Network Administration ',
       'Database Development ', 'Network Engineering ',
       'Software Trainee ', 'Dot Net Developer', 'Python Programmer ',
       'Full Stack Developer ', 'Data Process Executive ',
       'Trainee - Software Developer ', 'Node.js Backend Developer ',
       'IT And System Administrator ', 'Database Administrator ',
       'Software Engineer ', 'IT Executive ', 'IOS Developer ',
       'Remote Software Developer ', 'Quality Analyst ',
       'Data Scientist ', 'Python Developer ', 'Dot Net Developer ',
       'Full Stack Developer Intern ', 'Website Developer ',
       'IT Manager ', 'IT Assistant ', 'AWS Expert ',
       'Junior Web Developer ', 'Junior Software Developer ',
       'Offensive Security Engineer ', 'Product Security Engineer ',
       'Junior Associate ', 'Robotics ', 'Quality Analytics ',
       'Ethical Hacking ', 'Android/Flutter Development ', 'IT Intern ',
       'Java Developer ', 'Firmware Development ',
       'Python Engineer With GenAI ', 'IT Software Engineer ',
       'Software Engineer - Developer ', 'Software Developer ',
       'Application Software Developer ', 'XML Developer ',
       'Full Stack Development Intern ', 'SAP CPI ', 'NET Development ',
       'Product Analysis ', 'Frontend Developer', 'Jira Admin ',
       'SFDC Tester ', 'System Administrator',
       'Software Implementation Specialist ', 'VB.Net Developer ',
       'Salesforce Devops ', 'Computer Operator ',
       'Computer Technician/Support Specialist ', 'Shopify Developer ',
       'Node.js Development ', 'Frontend Web Designer ',
       'Software Testing Internship/ Training', 'System Operator',
       'Java Developer Or SQL Database Management Or Frontend Angular Js Expert ',
       'Web Developer ', 'Product Testing ', 'AI Technology ',
       'Zoho Developer Intern ', 'ASP.Net Developer MVC ',
       'Android Developer ', 'Full-Stack Developer Intern ',
       'System Operator ', 'Network System Administrator ',
       'PHP Developer ', 'Front-End Developers ', 'Web App Development ',
       'Mobile App Development (AI-Based) ', 'Backend Development ',
       'Node JS Developer ', 'PHP Laravel Developer ',
       'Embedded Systems - Firmware Development ',
       'Artificial Intelligence (AI) ', 'Flutter Developer ',
       'SOC Analyst ', 'Intern- Software Engineering ',
       'Trainee Implementation ', 'Developer ',
       'Geographic Mapper Or Mapping Technician ',
       'IMS - Integrated Management Systems ', 'Network Engineer ',
       'MERN Stack Developer ', 'Golang Developer ',
       'Network Automation And QA Intern ', 'Software Testing ',
       'Senior Kubernetes Engineer ', 'Java Intern', 'System Engineer ',
       'Senior WordPress Developer ',
       'React JS Developer / .NET Developer ', 'Front End Developer ',
       'React Developer ', 'Trainee Engineer ', 'HE Remote Work',
       'Software Developer Intern ', 'Junior Front End Developer ',
       'Laravel Developer ', 'Computer Assistant - Trainee ',
       'Android App And Web Developer ',
       'Software Development Engineering - Web Intern ',
       'Java Full Stack Development ', 'System Admin Executive ',
       'MIS Executive ', 'Data And Communication ', 'Manual Testing ',
       'AI Research ', 'Flutter Developer Fresher ',
       'Asp.net MVCC.Net Developer ',
       'Computer Hardware And Network Engineer ', 'Data Analyst Intern ',
       'Frontend Developer ', 'Project Lead Dotnet Developer ',
       'UI Designer ', 'Software Tester', 'Data Analyst',
       'Ataccama Admin ', 'Systems Engineer ', 'Data Analyst ',
       'Angular Developer ', 'Product Design And Enhancement ',
       'QA Fresher ', 'Android Application Developer ', 'IMS',
       'Java Developers ', 'IT Network Engineer ',
       'Generative AI Engineer ',
       'Full Stack Web Developer Intern/Trainee ',
       'ASP.NET Developer Intern ',
       'Senior Software Manager - Backend Engineer ',
       'Windchill Developer ', 'Software Intern ',
       'Technical Developer/Trainee ', 'Lead Consultant Angular ',
       'Senior System Admin ', 'Automation And Manual Testing ',
       'Sr. Python / Lead Engineer - REMOTE ',
       'Full Stack Web Developer ', 'Trainee - Web Developer ',
       'Dot Net Software Developer ', 'Software Trainee Engineer ',
       'Software Engineer Trainee ', 'IT Freshers ', 'Software Tester ',
       'Information Technology - Trainee ', 'Network Engineer - Fresher ',
       'Remote Front End Developer ',
       'Senior Backend Python Software Developer ',
       'PHP Laravel Developer Intern ', 'Junior Salesforce Developer ',
       'Junior Laravel Developer ', 'PHP/Laravel Developer ',
       'Machine Learning Engineer ', 'Full Stack WordPress Developer ',
       'Junior System Engineer ', 'QAQC Engineer ',
       'QA Automation Engineer ', 'Data Scientist Advanced Analytics ',
       'Data QA Analyst ', 'PHP WordPress And Shopify Developer ',
       'Junior Software Engineer/Software Developer Trainee ',
       'UI/UX Internship ', 'Automation Software Testing Intern ',
       'Fresher Developer ', 'Systems Trainee ',
       'C Plus Plus Embedded Engineer ', 'Automation Test Engineer ',
       'PHP Programmer ', 'Web Designer ', 'Application Developer '],
      dtype=object)

In [45]:
df['job_title'].value_counts()

job_title
PHP Programmer                             258
Software Engineer                          157
Java Developer                             112
Application Developer                      100
Web Designer                               100
                                          ...
Computer Technician/Support Specialist       1
Shopify Developer                            1
Node.js Development                          1
Software Testing Internship/ Training        1
Software Developer / Engineer                1
Name: count, Length: 210, dtype: int64

In [46]:
df['Location'].value_counts()

Location
Bangalore      55
Delhi          50
Mumbai         43
Pune           41
Chennai        41
               ..
Banaskantha     1
Dhanbad         1
Jamshedpur      1
Gwalior         1
Asansol         1
Name: count, Length: 363, dtype: int64

## To display Maximum rows in a data

In [48]:
pd.set_option("display.max_rows",None)
df

,job_title,Experience,Company,Salary,Location
0,Software Developer / Engineer,0,Rayapuri Media OPC Pvt Ltd,20000 - 40000,Hyderabad
1,Python Junior Software Engineer Web Scraping A...,1,Insytelli services,25000 - 35000,Bangalore
2,WordPress Development,0,Stirring Minds,NaN,Delhi
3,Web Development,0,Stirring Minds,NaN,Delhi
4,Full Stack Development,0,Stirring Minds,NaN,Delhi
5,Blockchain Development,0,Buddha Education Association Incorporation,NaN,Faridabad
6,Mobile App Development,0,Buddha Education Association Incorporation,NaN,Ahmedabad
7,Artificial Intelligence - AI,0,Buddha Education Association Incorporation,NaN,Chennai
8,Mobile App Development,0,Buddha Education Association Incorporation,NaN,Amritsar
9,Web Development,0,Avaari,NaN,Ahmedabad
10,Asp.net Development,0,Isourse,NaN,Delhi
11,Web Development,0,Shubh International,NaN,Ahmedabad
12,Big Data,0,The Overseas Consultant,NaN,Chennai
13,Software Development,0,TerraBlu Climate Technologies Private Limited,NaN,Pune
14,Game Development,0,MentorBoxx,NaN,Amritsar
15,Web Development,0,Dolphin Ad World Private Limited,NaN,Mumbai
16,Web Development,0,Buddha Education Association Incorporation,NaN,Akola
17,Product Management,0,Faclon,NaN,Mumbai
18,WordPress Development,0,Techsphere,NaN,Mumbai
19,Web Development,0,A Leading Company,NaN,Pune
20,Data Science,0,Faclon,NaN,Mumbai
21,Game Development,0,Creative Galileo,NaN,Pune
22,Cloud Computing Intern,0,Quantasis Private Limited,NaN,Mumbai
23,3D Unity Development,0,Perceived Design,NaN,Bangalore
24,Systems Development Engineer,0,COSGrid Systems Private Limited,NaN,Chennai
25,Front End Development,0,BUCKMINT,NaN,Delhi
26,Flutter Development,0,HealthFlex,NaN,Bangalore
27,Flutter Development,0,Antino Labs Private Limited,NaN,Delhi
28,Web Development,0,Synapse Valuetech Private Limited,NaN,Delhi
29,Android App Development,0,SBNRI - Simplifying Banking For NRIs,NaN,Delhi
31,Artificial Intelligence - AI,0,Shubh International,NaN,Ahmedabad
32,Laravel Development Intern,0,Xcrino Business Solutions,NaN,Delhi
33,Flutter Developer Intern,0,App Successor,10000 - 15000,Ghaziabad
34,WordPress Development,0,405 Gyp Aggregate Co,NaN,Delhi
35,.NET Development,0,Isourse,NaN,Delhi
37,Front End Development,0,COSGrid Systems Private Limited,NaN,Chennai
38,Android App Development,0,MyUpchar,NaN,Delhi
39,Reactjs Development,0,One Card Solution Pvt Limited,NaN,Delhi
40,AWS DevOps Engineer,0,AgentInsights,NaN,Delhi
41,PHP And Laravel Developers,0,Radiant Tech Solutions,NaN,Delhi
42,Python Development,0,Datannovitesol LLP,NaN,Pune
43,Embedded Systems,0,Ground Screw Private Limited,NaN,Pune
44,QA Testing,0,Telosa,NaN,Pune
45,SAP HANA (S/4) Consulting,0,Ajspire Technologies Pvt. Ltd,NaN,NaN
46,PHP Development,0,ADG Online Solutions Private Limited,NaN,Delhi
47,Large Language Model Researcher,0,AgentInsights,NaN,Delhi
48,Full Stack Development,0,Faith App,NaN,Delhi
49,Python Development,0,HASHCRON TECHNOLOGIES,NaN,Mumbai
50,Data Analytics,0,Inquizity,NaN,Navi Mumbai
51,JavaScript Developer,0,Arch Store,NaN,Mumbai
52,Data Analytics,0,AN QUANTECH LLP,NaN,Delhi
53,Data Science,0,Quantasis Private Limited,NaN,Mumbai
54,Python Development,0,FIKAA,NaN,Mumbai
55,Flutter Development,0,Quantasis Private Limited,NaN,Mumbai
56,System & Network Administration,0,GAMSYS Tech Private Limited,NaN,NaN
57,Full Stack Development,0,GAMSYS Tech Private Limited,NaN,NaN
58,Database Development,0,Triumph System And Solutions Private Limited,NaN,Mumbai
59,Mobile App Development,0,FIKAA,NaN,Mumbai
60,Network Engineering,0,Treya Wireless Private Limited,NaN,Mumbai
61,Flutter Development,0,Kenmark ITan Solutions,NaN,Mumbai
62,Software Trainee,0,WinQSys Software Solutions,2500 - 4000,Chennai
63,Software Trainee,0,WinQSys Software Solutions,2500 - 4000,Chennai
64,Dot Net Developer,0,Nuuqe systems,NaN,Bhubaneswar
65,Python Programmer,0,Panacorp Software Company,12000 - 20000,Nagercoil
66,Full Stack Developer,0,NnN Net Solutions,10000 - 15000,Chennai
67,Data Process Executive,0,Tolzitech solutions PVT LTD,18000,Hyderabad
68,Trainee - Software Developer,0,NitcoInc,15000,Hyderabad
69,Software Trainee,0,ToXSL Technologies Pvt Ltd.,5000 - 10000,Mohali
70,Node.js Backend Developer,0,JGN TECHNOLOGIES,10000 - 12000,Chennai
71,IT And System Administrator,3,Datamate Info Solutions Limited,NaN,Kochi
72,Database Administrator,3,Datamate Info Solutions Limited,NaN,Kochi
73,Software Engineer,0,Verve Systems Pvt Ltd,NaN,Ahmedabad
74,IT Executive,0,Gsm.pvt.ltd,NaN,Patna
75,IOS Developer,0,Significant Infotech,NaN,Surat
76,Remote Software Developer,0,Futurionic Private LImited,5000,Delhi
77,Quality Analyst,0,LiveChek Pvt Tld,NaN,Delhi
78,Data Scientist,0,Teacher technologies pvt ltd,25000 - 40000,Chennai
79,Data Scientist,3,TEACHERS TECHNOLOGIES PVT LTD,25000 - 40000,Chennai
80,Python Developer,4,Iappsdata,45000 - 100000,Bangalore
81,Dot Net Developer,4,Webplat,NaN,Pune
82,Full Stack Developer,3,TekCrewz Pvt Ltd,7000 - 20000,Thanjavur
83,Full Stack Developer Intern,0,Vplak india pvt ltd,NaN,Gurgaon
84,Website Developer,0,Global India Express,15000 - 20000,Delhi
85,IT Manager,4,Ideal Career Zone,15000 - 16000,Kolkata
86,IT Assistant,0,Kothari International School,NaN,Noida
87,AWS Expert,4,AIIP,20000 - 25000,Delhi
89,Junior Web Developer,0,Bit Binders,NaN,Delhi
90,Junior Software Developer,0,SOTIInc,25000 - 30000,Bangalore
91,Offensive Security Engineer,4,TQuanta Technologies Private Limited,NaN,Hyderabad
92,Product Security Engineer,4,TQuanta Technologies Private Limited,NaN,Hyderabad
93,Junior Associate,0,Whitestone Software Solutions Private Limited,30000 - 35000,Delhi
94,Robotics,0,ERIC Robotics PSIPL,NaN,Pune
95,Quality Analytics,0,Roziroti.work,NaN,Pune
96,Ethical Hacking,0,TecheirKonseptrix Analytics Private Limited,NaN,Mumbai
97,Android/Flutter Development,0,GAMSYS Tech Private Limited,NaN,NaN
98,Mobile App Development,0,Neubotz Technologies Private Limited,NaN,Bangalore
99,IT Intern,0,Pawzz,NaN,Delhi
100,Java Developer,0,Inspironlabs Software Systems Private Limited,NaN,Bangalore
101,Full Stack Development,0,Ensemble Control Incorporation,NaN,Bangalore
102,Mobile App Development,0,Bempu Health,NaN,Bangalore
103,Firmware Development,0,ReVx Energy,NaN,Bangalore
104,Python Engineer With GenAI,3,Athmick,20000 - 50000,Bangalore
105,IT Software Engineer,0,DSK SOFTWARE SOLUTIONS PVT.LTD,30000 - 40000,Hyderabad
106,Dot Net Developer,0,Percept Infosystem,5000 - 15000,Nagpur
107,Java Developer,0,AMC Career,29000 - 47000,Pune
108,Java Developer,0,AMC Career,29000 - 47000,Pune
109,Software Engineer - Developer,0,AMC Career,29000 - 47000,Pune
110,Software Engineer,0,AMC Career,29000 - 47000,Pune
111,Software Developer,0,AMC Career,29000 - 47000,Pune
112,IT Software Engineer,0,AMC Career,29000 - 47000,Pune
113,Application Software Developer,0,AMC Career,29000 - 47000,Pune
114,XML Developer,0,Shree Aryavarta Infotech,NaN,Mancherial
115,Full Stack Development Intern,0,Faith App,NaN,Mumbai
116,Android App Development,0,Invizio Solutions LLP,NaN,Mumbai
117,SAP CPI,4,Tetra fount,NaN,Bangalore
118,Web Development,0,Param Hansa Philanthropies - PHP,NaN,Bangalore
119,NET Development,0,Siemens,NaN,Bangalore
120,Product Analysis,0,ClearTax,NaN,Bangalore
121,IT Software Engineer,0,A Leading MNC,NaN,Pune
122,Frontend Developer,0,Percept Infosystem,5000 - 15000,Nagpur
123,Jira Admin,4,VY Systems,NaN,Bangalore
124,SFDC Tester,4,Vy systems,170000 - 270000,Hyderabad
125,System Administrator,0,Adithya it solution,10000 - 12000,Salem
126,Software Implementation Specialist,0,Unipro tech solutions pvt ltd,NaN,Chennai
127,Java Developer,0,Percept Infosystem,5000 - 15000,Nagpur
128,VB.Net Developer,4,RLE India,NaN,Chennai
129,Salesforce Devops,0,CloudNextGen IT Software Solutions,NaN,Mathura
130,Computer Operator,0,Adithya it solution,13000 - 15000,Salem
131,Computer Technician/Support Specialist,0,J K S S & Associates,15000 - 25000,Delhi
132,Shopify Developer,3,610 Web Lab,20000 - 50000,Chandigarh
133,Python Development,0,Antino Labs Private Limited,NaN,Gurgaon
134,Node.js Development,0,Antino Labs Private Limited,NaN,Bangalore
135,Software Engineer - Developer,0,Apex falcon technologies,10000,Bangalore
136,Frontend Web Designer,0,Noris,NaN,Hyderabad
137,Software Testing Internship/ Training,0,Percept Infosystem,5000 - 15000,Nagpur
138,System Operator,0,Adithya it Solution Pvt Ltd,22000 - 23000,Salem
139,Java Developer Or SQL Database Management Or F...,0,Intelligrow Consultancy Services Pvt Ltd,NaN,Hubli
140,Web Developer,0,MS Selvam Softech .,NaN,Sivakasi
141,Full Stack Development,0,Cure And Care Wellness Private Limited,NaN,Bangalore
142,Network Engineering,4,Oncospark India Private Limited,NaN,Chennai
143,Web Development,0,Gully Classes Foundation,NaN,Mumbai
144,Product Testing,0,ISAMAY,NaN,Mumbai
145,AI Technology,0,Clipbait Media Private Limited,NaN,Bangalore
146,Zoho Developer Intern,0,Providian Global Solutions Privet Limited,NaN,Akola
147,Mobile App Development,0,Center For International Promotion Of Sports &...,NaN,Pune
148,ASP.Net Developer MVC,4,Auctech Marketing & Communication Pvt. Ltd.,20000 - 30000,Lucknow
149,Android Developer,0,Significant Infotech,2000 - 40000,Surat
150,Full Stack Developer,4,Vision tech,100000 - 125000,Delhi
151,Full-Stack Developer Intern,0,Reputed Company,NaN,Hyderabad
152,System Operator,0,Adithya it Solution Pvt Ltd,13000 - 15000,Salem
153,Network System Administrator,0,Adithya it Solution Pvt Ltd,15000 - 18000,Salem
154,System Operator,0,Adithya it solution,13000 - 15000,Salem
155,Network System Administrator,0,Adithya it solution,15000 - 18000,Salem
156,Full-Stack Developer Intern,0,Company Name Confidential,2000 - 3000,Nellore
157,Full Stack Developer,2,Alpha Solutions,20000 - 30000,Coimbatore
158,PHP Developer,0,Satej Infotech Pvt Ltd.,5000 - 8000,Kolhapur
159,Front-End Developers,0,Kenmark ITan Solutions,NaN,Mumbai
160,Web App Development,0,Greendzine Technologies,NaN,Bangalore
162,Asp.net Development,1,Quantasis Private Limited,NaN,Mumbai
163,Mobile App Development (AI-Based),0,Greendzine Technologies,NaN,Bangalore
164,Backend Development,0,Digi India Solutions,NaN,NaN
165,Web Developer,0,ANWENTEC INNOVATION PVT LTD,5000 - 10000,Hyderabad
166,Node JS Developer,2,Ellifi,NaN,Surat
167,PHP Laravel Developer,4,Deepaul Technologies Private Limited,50000 - 70000,Delhi
168,Embedded Systems - Firmware Development,0,Greendzine Technologies,NaN,Bangalore
170,Artificial Intelligence (AI),0,Uboard India Limited,NaN,Delhi
171,Backend Development,0,FreightCrate,NaN,Mumbai
172,Full Stack Development,0,Faith App,NaN,Mumbai
173,Front End Development,0,Faith App,NaN,Mumbai
174,Embedded Systems,0,Improvians,NaN,Mumbai
175,WordPress Development,0,Lets Meet Bro,NaN,Bangalore
176,Web Developer,3,Web Cookies,20000 - 25000,Delhi
177,Computer Operator,0,VISS SOLUTIONS,6000 - 12000,Raebareli
179,Flutter Developer,2,MIS Work India Pvt Ltd,40000 - 80000,Delhi
180,SOC Analyst,0,BM Infotrade,8000,Jaipur
181,PHP Developer,2,MIS Work India Pvt Ltd,30000 - 70000,Delhi
182,Data Analytics,0,Uboard India Limited,NaN,Delhi
183,Intern- Software Engineering,0,Mayura Consultancy,NaN,Bangalore
184,Software Engineer,0,Elevate Management Services,NaN,Bangalore
185,Trainee Implementation,0,Datamate Info Solutions Limited,NaN,Thiruvananthapuram
186,Data Scientist,0,ADITHYA IT SOLUTIONS PRIVATE LTD,20000 - 25000,Salem
187,Developer,0,Adithya it Solution Pvt Ltd,25000 - 37500,Salem
188,Geographic Mapper Or Mapping Technician,0,Adithya it Solution Pvt Ltd,15000 - 20000,Salem
189,IMS - Integrated Management Systems,0,Adithya it Solution Pvt Ltd,20000 - 25000,Salem
190,Network Engineer,0,Adithya it Solution Pvt Ltd,25000 - 30000,Salem
191,MERN Stack Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,15000 - 20000,Salem
192,IT Software Engineer,0,Adithya it Solution Pvt Ltd,25000 - 30000,Salem
193,Golang Developer,0,LineupX,NaN,Mumbai
196,Data Analytics,0,Stayfari India Private Limited,NaN,Delhi
197,Network Automation And QA Intern,1,COSGrid Systems Private Limited,NaN,Chennai
198,Software Testing,0,Alluvium IoT Solutions Private Limited,NaN,Ahmedabad
199,QA Testing,0,EVision IT Solution Private Limited,NaN,Ahmedabad
200,Python Development,0,Charmeuse Technologies Private Limited,NaN,Ahmedabad
201,Front End Development,0,Sirma Business Consulting India Private Limited,NaN,Bangalore
202,Backend Development,0,Aracknoid Future Labs,NaN,Jaipur
203,Flutter Development,0,Vigorous Healthtech Private Limited,NaN,Jaipur
204,WordPress Development,0,PSPTECH Hub Services Private Limited,NaN,Warangal
205,Software Development,0,Leading Firm,NaN,Hyderabad
206,Flutter Development,0,Mobioxy,NaN,Ahmedabad
207,Senior Kubernetes Engineer,4,TQuanta Technologies Private Limited,NaN,Hyderabad
208,Java Intern,0,Percept Infosystem,5000 - 15000,Nagpur
209,System Engineer,0,Adithya it Solution Pvt Ltd,16000 - 22000,Salem
210,Senior WordPress Developer,0,CXO Enterprises Private Limited,34000 - 50000,Bangalore
211,Dot Net Developer,1,Trios Software PVt,NaN,Virudhunagar
212,Python Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,15000 - 20000,Salem
213,React JS Developer / .NET Developer,2,Trios Software PVt,NaN,Virudhunagar
214,Front End Developer,1,Walstar Technology,NaN,Kolhapur
215,React Developer,1,Walstar Technology,NaN,Kolhapur
216,Trainee Engineer,0,Safi engineering solutions,NaN,Pune
217,HE Remote Work,0,HE pvt ltd,4000 - 6000,Raipur
218,Software Developer Intern,0,Skill decode tech,NaN,Chennai
219,Junior Front End Developer,2,Plico LLC,20000 - 43000,Delhi
220,Laravel Developer,0,Kirikaa Digital,12000 - 35000,Durgapur
221,Computer Assistant - Trainee,0,Mother India Life Spaces and Infra Engineering...,NaN,Hyderabad
222,Full Stack Developer,2,Jumbl,35000,Noida
223,Android App And Web Developer,2,Greenin Urja,8000 - 20000,Dehradun
224,Software Development Engineering - Web Intern,0,PiSence Technologies LLP,NaN,Chennai
225,Java Full Stack Development,0,TecheirKonseptrix Analytics Private Limited,NaN,NaN
226,Data Science,0,Boston Institute Of Analytics Global Education...,NaN,Mumbai
227,Android App Development,0,One Card Solution Pvt Limited,NaN,Delhi
228,System Admin Executive,0,White House Business Solutions Pvt Ltd,15000 - 20000,Chennai
229,MIS Executive,0,Awsense,20000 - 26000,Mumbai
231,Flutter Developer,0,Techzai Innovations,NaN,Hyderabad
232,Data And Communication,0,Centre For Knowledge And Development,NaN,Delhi
233,Data Science,0,Innovation Hack,NaN,Mumbai
234,Manual Testing,0,AntWalk,NaN,Bangalore
235,AI Research,0,Elementals,NaN,Bangalore
236,Web Development,0,Elecnovo Private Limited,NaN,Bangalore
237,Python Development,0,Akash startup,NaN,Delhi
238,Software Trainee,0,Rapsys Info Tech,3000,Chennai
239,Flutter Developer Fresher,0,Acuratech Global,10000 - 15000,Mohali
240,Data Scientist,4,Fxis AI,40000,Ahmedabad
241,Asp.net MVCC.Net Developer,2,Palladsys Software Solutions,NaN,Hyderabad
242,Computer Hardware And Network Engineer,0,Microsun Infocare Pvt Ltd,15000 - 25000,Bangalore
243,Data Analyst Intern,0,Galytix Analytics Pvt. Ltd.,NaN,Gurgaon
244,Frontend Developer,0,Soniio,NaN,Kolkata
245,Full Stack Developer,4,King Worldwide,15000 - 25000,Mumbai
246,Project Lead Dotnet Developer,4,Arrising Talent,NaN,Ahmedabad
247,Java Developer,0,Techvolt software,15000 - 20000,Coimbatore
248,Java Developer,0,Techvolt,15000 - 30000,Coimbatore
249,Full Stack Developer,0,Pipe recruit,NaN,Delhi
250,Software Engineer,2,INFOSQUARE GLOBAL SOLUTIONS PRIVATE LIMITED,15000 - 50000,Bangalore
251,UI Designer,1,Contact 360,NaN,Kolkata
252,Software Tester,0,Adithya IT Solutions Pvt Ltd,25000 - 30000,Salem
253,Software Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
254,Data Analyst,0,Adithya IT Solutions Pvt Ltd,25000 - 30000,Salem
255,Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
256,Software Engineer,2,Agenda technologies,15000 - 50000,Bangalore
257,Ataccama Admin,4,Future Forward BPO,NaN,Gurgaon
258,Dot Net Developer,2,Zibma Infotech,NaN,Surat
259,Systems Engineer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
260,Data Analyst,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
261,Flutter Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
262,Angular Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,20000 - 25000,Salem
263,Full Stack Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
264,Product Design And Enhancement,4,Infosysinc,NaN,Bangalore
265,QA Fresher,0,TechRAQ Info Solutions Pvt Ltd,11111,Hyderabad
266,Android Application Developer,2,Homeland megahartz private limited,5000 - 7500,Bangalore
267,IMS,0,ADITHYA IT SOLUTION,20000 - 25000,Salem
269,Dot Net Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
270,Java Developers,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
271,Python Developer,0,ADITHYA IT SOLUTIONS PRIVATE LTD,NaN,Salem
272,IT Network Engineer,0,Youtag infotag,2000 - 15000,Chennai
273,Generative AI Engineer,2,AI Generative,25000 - 40000,Hyderabad
274,PHP Developer,0,Phavio software,NaN,Nellore
275,Full Stack Web Developer Intern/Trainee,0,EarnXP,NaN,Chennai
276,PHP Developer,4,ASK Innovations,30000 - 50000,Indore
277,ASP.NET Developer Intern,0,Quartz technologies,4000 - 6000,Kanpur
278,Software Trainee,0,TalentBridge Technologies Pvt Ltd,NaN,Bangalore
279,Senior Software Manager - Backend Engineer,4,Streamoid Technologies Private Limited,300000 - 350000,Bangalore
280,Python Developer,4,Srijan Spectrum,170000 - 200000,Hyderabad
281,Windchill Developer,4,Srijan Spectrum,180000 - 300000,Bangalore
282,Full Stack Developer,0,Kisan 365,NaN,Guntur
283,Software Engineer,4,Ideal Career Zone,50000 - 60000,Kolkata
284,Flutter Developer,1,Live fx,15000 - 30000,Bangalore
285,IOS Developer,0,Optiquall Solutions,NaN,Pune
286,Python Developer,2,Alite Projects,12000 - 15000,Vadodara
287,Full Stack Developer,0,App Innovation Technologies,NaN,Chennai
288,Software Intern,0,Wizinoa,NaN,Madurai
289,Technical Developer/Trainee,1,Apps Business IT Solutions Private Limited,NaN,Chennai
290,Frontend Web Designer,0,Topflow Technology Services Private Limited,5000 - 15000,Kolkata
291,Lead Consultant Angular,4,HIRD,58000 - 60000,Hyderabad
292,Senior System Admin,4,Ultrafly Solution Private Limited,NaN,Coimbatore
293,Automation And Manual Testing,0,SMART ENTRY IT INFRASTRUCTURE,NaN,Chennai
294,Network Engineer,1,SMART ENTRY IT INFRASTRUCTURE,NaN,Chennai
295,MERN Stack Developer,0,WizInoa,15000 - 25000,Madurai
296,Data Analytics,0,Greenovative Energy Private Limited,NaN,Pune
297,Sr. Python / Lead Engineer - REMOTE,4,Anvayainfosolutions,83000 - 250000,Bangalore
298,Full Stack Web Developer,0,Associative,5000,Pune
299,Trainee - Web Developer,0,Somayu Infotech,NaN,Pune
300,Dot Net Software Developer,0,Zelite Solutions,10000 - 15000,Mumbai
301,Software Trainee Engineer,0,TalentBridge Technologies Pvt Ltd,25000,Bangalore
302,Software Engineer Trainee,0,TalentBridge Technologies Pvt Ltd,25000,Bangalore
303,Software Engineer,0,Enrgy Money,50000 - 250000,Chandigarh
304,IT Freshers,0,NetTech India,NaN,Mumbai
305,Software Tester,0,Qtest software testing,10000 - 15000,Kozhikode
306,Information Technology - Trainee,1,Kirloskar Electric Company LTD,NaN,Bangalore
307,Java Developer,2,SPHINAX INFO SYSTEM,18000 - 30000,Chennai
308,Network Engineer - Fresher,1,IT Career Challenge Technology Solutions Pvt Ltd,NaN,Chennai
309,Network Engineer,0,SMART ENTRY IT INFRASTRUCTURE,15000 - 30000,Chennai
310,Remote Front End Developer,3,ACA Software Solutions,25000 - 29000,Noida
311,Java Developer,2,Randstad,NaN,Hyderabad
312,Java Developer,4,Rigel Networks Pvt Ltd,NaN,Mumbai
313,System Engineer,0,KR Technologies,8000 - 15000,Tiruppur
314,Senior Backend Python Software Developer,4,Sludge AI,50000 - 58333,Delhi
315,Software Developer,0,Realty Tech Solutions,NaN,Bhilwara
316,Data Science,0,YoungMinds Technology Solutions Pvt Ltd,NaN,Tirupati
317,PHP Laravel Developer Intern,1,QuantaPIxel Software Solutions,3000 - 5000,Hyderabad
318,Data Scientist,0,YoungMinds Technology Solutions Pvt Ltd,NaN,Tirupati
319,Full Stack Developer,0,Cynosure Corporate Solutions,NaN,Chennai

In [49]:
df.to_csv("freshers_world.csv",index=False)

In [89]:
df['Location'].value_counts()

Location
Bangalore                      55
Delhi                          50
Mumbai                         43
Pune                           41
Chennai                        41
Salem                          33
Hyderabad                      32
Ahmedabad                      20
Kolkata                        13
Gurgaon                        13
Surat                          11
Noida                          11
Tirupati                        9
Nellore                         8
Kochi                           8
Chandigarh                      8
Madurai                         8
Jaipur                          8
Nagpur                          8
Silchar                         7
South Goa                       7
Coimbatore                      7
Tawang                          7
Guntur                          7
Itanagar                        7
Vijayawada                      7
Patna                           7
Port Blair                      7
Raipur                          7
Guwahati                        7
Nicobar                         7
Thiruvananthapuram              6
Indore                          6
Kanpur                          6
Kolhapur                        6
Hubli                           6
Silvassa                        6
Bhubaneswar                     6
Visakhapatnam                   6
Erode                           5
Rajahmundry                     5
Kozhikode                       5
Kurnool                         5
Jaisalmer                       5
Amritsar                        5
Shimla                          5
Panaji                          5
Machilipatnam                   5
Porbandar                       5
Srikakulam                      5
Faridabad                       5
Vizianagaram                    5
Wayanad                         5
Anantapur                       5
Guntakal                        4
Eluru                           4
Kakinada                        4
Dibrugarh                       4
Srinagar                        4
Ajmer                           4
Rajkot                          4
Hooghly                         4
Aizawal                         4
Lakshadweep                     4
Panipat                         4
Mysore                          4
Agartala                        4
Kolar                           4
Muzaffarpur                     4
Kollam                          4
Roorkee                         4
Nagaon                          4
Mandi                           4
Warangal                        4
Nagercoil                       4
Gandhinagar                     4
Vadodara                        4
Navi Mumbai                     4
Varanasi                        3
Gariaband                       3
East Godavari                   3
Ongole                          3
Kadapa                          3
Jammu                           3
Allahabad                       3
Dharmasala                      3
Ambala                          3
Sivasagar                       3
Ujjain                          3
Aurangabad                      3
Hosur                           3
Lucknow                         3
Jorhat                          3
Hisar                           3
Chikkamagaluru                  3
Washim                          3
Faizabad                        3
Kulu                            3
Rewa                            3
Ankleshwar                      3
Bhavnagar                       3
Tuticorin                       3
Udaipur                         3
Tirunalveli                     3
Raigarh                         3
Bhilai                          3
Bellary                         3
Shillong                        3
Vapi                            3
Thrissur                        3
Idukki                          3
Rourkela                        3
Korba                           3
Durg                            3
Gaya                            2
Godhra                          2
Virudhunagar                    2
Durgapur                        2
Dehradun                        2
Mandya                          2
Raichur                         2
North Sikkim                    2
Tiruppur                        2
Palakkad                        2
Bharuch                         2
Navsari                         2
Rohtas                          2
Vaishali                        2
Jodhpur                         2
Bhagalpur                       2
Akola                           2
Darjeeling                      2
Mehsana                         2
Gandhidham                      2
Paradeep                        2
Kavaratti                       2
Sivakasi                        2
Imphal                          2
Ahmednagar                      2
Agra                            2
Meerut                          2
Nizamabad                       2
Mohali                          2
Rohtak                          2
Rewari                          2
Kota                            2
Alappuzha                       2
Mayabunder                      2
Ghaziabad                       2
Pathanamthitta                  2
Malappuram                      2
Longding                        2
Dibang Valley                   2
Kottayam                        2
Kannur                          2
Thanjavur                       2
Cuttack                         2
Mathura                         2
Junagadh                        2
Balrampur (Chattisgarh)         2
Golaghat                        2
Chirang                         2
Karimganj                       2
Hojai                           2
Dhamtari                        2
Dima Hasao                      2
Janjgir-Champa                  2
Dhemaji                         2
Kabirdham                       2
Kondagaon                       2
Lakhimpur                       2
Mahasamund                      2
Narayanpur                      2
Sukma                           2
South Salmara-Mankachar         2
Surguja                         2
Bongaigaon                      2
Bilaspur                        2
Bijapur(Chattisgarh)            2
Morigaon                        2
Dantewada                       2
West Karbi Anglong              2
Majuli                          2
Kokrajhar                       2
Karbi Anglong                   2
Hailakandi                      2
Goalpara                        2
Dhubri                          2
Tinsukia                        2
Darrang                         2
Sonitpur                        2
Balod                           2
Bastar                          2
Charaideo                       2
Bishwanath                      2
Baksa                           2
Bemetara                        2
Udalguri                        2
Barpeta                         2
Nalbari                         2
Belgaum                         2
Kurung Kumey                    2
Kanker                          2
Jashpur                         2
Tirap                           2
Haveri                          2
East Siang                      2
Lower Siang                     2
Lower Subansiri                 2
Lower Dibang Valley             2
Koriya                          2
West Siang                      2
Pondicherry                     2
Mungeli                         2
Changlang                       2
West Kameng                     2
Rajnandgaon                     2
Ooty                            2
Surajpur                        2
Jamnagar                        2
Namsai                          2
Anjaw                           2
East Kameng                     2
Kra Daadi                       2
Lohit                           2
Siang                           2
Upper Siang                     2
Valsad                          2
Hassan                          2
Papum Pare                      2
Katihar                         1
Shivamogga                      1
Jamui                           1
Kaimur                          1
Kishanganj                      1
Chamarajnagar                   1
Patiala                         1
Gadag                           1
Samastipur                      1
Munger                          1
Darbhanga                       1
West Champaran                  1
Supaul                          1
Sitamarhi                       1
Sheikhpura                      1
Madhubani                       1
East Champaran                  1
Arwal                           1
Lakhisarai                      1
Sultanpur                       1
Leh                             1
Banka                           1
Araria                          1
Purnia                          1
Birbhum                         1
Koppal                          1
Adilabad                        1
Aligarh                         1
Uttarkashi                      1
Kashipur                        1
Bageshwar                       1
Rudrapur                        1
Haridwar                        1
Nainital                        1
Karimnagar                      1
Jhansi                          1
Medak                           1
Purba Medinipur                 1
Nawada                          1
Haldia                          1
Jalpaiguri                      1
Kharagpur                       1
Siliguri                        1
Gorakhpur                       1
Amethi                          1
Bijapur                         1
Tumakuru                        1
Gulbarga                        1
Bidar                           1
Yadgir                          1
Udupi                           1
Chitradurga                     1
Ramanagara                      1
Bardhaman                       1
Chikkaballapur                  1
Gangtok                         1
Hubli-Dharwad                   1
Davanagere                      1
Mangalore                       1
Dharwad                         1
Alwar                           1
West Sikkim                     1
Namchi                          1
Madhepura                       1
Mahendragarh                    1
Saharsa                         1
Karnal                          1
Jind                            1
Fatehabad                       1
Yamunanagar                     1
Panchkula                       1
Kaithal                         1
Sonipat                         1
Nuh                             1
Saran                           1
Jhajjar                         1
Charkhi Dadri                   1
Palwal                          1
Bhiwani                         1
Kurukshetra                     1
Howrah                          1
Sirsa                           1
Dalhousie                       1
Chamba                          1
Hamirpur                        1
Solan                           1
Kangra                          1
Bilaspur (Himachal Pradesh)     1
Sirmaur                         1
Anantnag                        1
Mancherial                      1
Raebareli                       1
Bhilwara                        1
Bharatpur                       1
Bikaner                         1
Barmer                          1
West Tripura                    1
Pudukkottai                     1
Ranchi                          1
Vellore                         1
Jabalpur                        1
Cuddalore                       1
Sheohar                         1
Siwan                           1
Khagaria                        1
Jehanabad                       1
Gopalganj                       1
Begusarai                       1
Aurangabad (Bihar)              1
Buxar                           1
Hajipur                         1
Biharsharif                     1
Arrah                           1
Wardha                          1
Banaras                         1
Bathinda                        1
Tiruvottiyur                    1
Bhopal                          1
Avadi                           1
Morbi                           1
Patan                           1
Anand                           1
Bhuj                            1
Gir                             1
Kandla                          1
Surendranagar                   1
Dahod                           1
Amreli                          1
Banaskantha                     1
Dhanbad                         1
Jamshedpur                      1
Gwalior                         1
Asansol                         1
Name: count, dtype: int64

In [105]:
df['job_title'].value_counts()

job_title
PHP Programmer                                                              258
Software Engineer                                                           157
Java Developer                                                              112
Application Developer                                                       100
Web Designer                                                                100
Front End Developer                                                          98
Automation Test Engineer                                                     82
Full Stack Developer                                                         12
Web Development                                                              10
Software Developer                                                            8
PHP Developer                                                                 8
Web Developer                                                                 6
Full Stack Development                                                        6
Mobile App Development                                                        6
IT Software Engineer                                                          6
Flutter Development                                                           6
Python Development                                                            6
Data Scientist                                                                5
Python Developer                                                              5
Data Analytics                                                                5
Flutter Developer                                                             5
WordPress Development                                                         5
Data Science                                                                  5
Software Trainee                                                              5
Android App Development                                                       4
Front End Development                                                         4
Dot Net Developer                                                             4
Network Engineer                                                              3
Dot Net Developer                                                             3
Backend Development                                                           3
Software Engineer - Developer                                                 3
Systems Engineer                                                              2
Software Intern                                                               2
Artificial Intelligence - AI                                                  2
Application Software Developer                                                2
Game Development                                                              2
Computer Operator                                                             2
Frontend Web Designer                                                         2
Frontend Developer                                                            2
System Operator                                                               2
IOS Developer                                                                 2
Android Developer                                                             2
Full-Stack Developer Intern                                                   2
Network System Administrator                                                  2
Developer                                                                     2
MERN Stack Developer                                                          2
Computer Hardware And Network Engineer                                        2
Asp.net Development                                                           2
System Engineer                                                               2
Network Engineering                                                           2
Embedded Systems                                                              2
Software Development                                                          2
QA Testing                                                                    2
Flutter Developer Fresher                                                     1
Data And Communication                                                        1
Junior Software Engineer/Software Developer Trainee                           1
Manual Testing                                                                1
AI Research                                                                   1
Asp.net MVCC.Net Developer                                                    1
Software Tester                                                               1
PHP WordPress And Shopify Developer                                           1
Data QA Analyst                                                               1
Data Analyst Intern                                                           1
Data Scientist Advanced Analytics                                             1
QA Automation Engineer                                                        1
QAQC Engineer                                                                 1
Project Lead Dotnet Developer                                                 1
MIS Executive                                                                 1
System Admin Executive                                                        1
Java Full Stack Development                                                   1
Fresher Developer                                                             1
Senior WordPress Developer                                                    1
React JS Developer / .NET Developer                                           1
Blockchain Development                                                        1
C Plus Plus Embedded Engineer                                                 1
Systems Trainee                                                               1
React Developer                                                               1
Trainee Engineer                                                              1
HE Remote Work                                                                1
UI/UX Internship                                                              1
Software Developer Intern                                                     1
Junior Front End Developer                                                    1
Automation Software Testing Intern                                            1
Laravel Developer                                                             1
Computer Assistant - Trainee                                                  1
Android App And Web Developer                                                 1
Software Development Engineering - Web Intern                                 1
UI Designer                                                                   1
Remote Front End Developer                                                    1
Junior System Engineer                                                        1
Dot Net Software Developer                                                    1
Technical Developer/Trainee                                                   1
Lead Consultant Angular                                                       1
Senior System Admin                                                           1
Automation And Manual Testing                                                 1
Sr. Python / Lead Engineer - REMOTE                                           1
Full Stack Web Developer                                                      1
Trainee - Web Developer                                                       1
Software Trainee Engineer                                                     1
Network Engineer - Fresher                                                    1
Software Engineer Trainee                                                     1
IT Freshers                                                                   1
Software Tester                                                               1
Junior Salesforce Developer                                                   1
PHP Laravel Developer Intern                                                  1
Senior Backend Python Software Developer                                      1
Information Technology - Trainee                                              1
Junior Laravel Developer                                                      1
Windchill Developer                                                           1
Senior Software Manager - Backend Engineer                                    1
Java Intern                                                                   1
Ataccama Admin                                                                1
Data Analyst                                                                  1
Angular Developer                                                             1
Product Design And Enhancement                                                1
QA Fresher                                                                    1
Android Application Developer                                                 1
IMS                                                                           1
Java Developers                                                               1
IT Network Engineer                                                           1
Generative AI Engineer                                                        1
Full Stack WordPress Developer                                                1
Machine Learning Engineer                                                     1
PHP/Laravel Developer                                                         1
Full Stack Web Developer Intern/Trainee                                       1
ASP.NET Developer Intern                                                      1
Data Analyst                                                                  1
Node JS Developer                                                             1
Senior Kubernetes Engineer                                                    1
IT And System Administrator                                                   1
Big Data                                                                      1
IT Executive                                                                  1
Remote Software Developer                                                     1
Quality Analyst                                                               1
Full Stack Developer Intern                                                   1
Website Developer                                                             1
IT Manager                                                                    1
IT Assistant                                                                  1
AWS Expert                                                                    1
Junior Web Developer                                                          1
Junior Software Developer                                                     1
Offensive Security Engineer                                                   1
Product Security Engineer                                                     1
Junior Associate                                                              1
Robotics                                                                      1
Quality Analytics                                                             1
Ethical Hacking                                                               1
Database Administrator                                                        1
Node.js Backend Developer                                                     1
Software Testing                                                              1
Trainee - Software Developer                                                  1
Cloud Computing Intern                                                        1
3D Unity Development                                                          1
Systems Development Engineer                                                  1
Laravel Development Intern                                                    1
Flutter Developer Intern                                                      1
.NET Development                                                              1
Reactjs Development                                                           1
AWS DevOps Engineer                                                           1
PHP And Laravel Developers                                                    1
SAP HANA (S/4) Consulting                                                     1
PHP Development                                                               1
Large Language Model Researcher                                               1
JavaScript Developer                                                          1
System & Network Administration                                               1
Database Development                                                          1
Python Programmer                                                             1
Data Process Executive                                                        1
Android/Flutter Development                                                   1
IT Intern                                                                     1
Firmware Development                                                          1
Python Engineer With GenAI                                                    1
ASP.Net Developer MVC                                                         1
System Operator                                                               1
Python Junior Software Engineer Web Scraping And Automation Entry Level       1
Front-End Developers                                                          1
Web App Development                                                           1
Mobile App Development (AI-Based)                                             1
Product Management                                                            1
PHP Laravel Developer                                                         1
Embedded Systems - Firmware Development                                       1
Artificial Intelligence (AI)                                                  1
SOC Analyst                                                                   1
Intern- Software Engineering                                                  1
Trainee Implementation                                                        1
Geographic Mapper Or Mapping Technician                                       1
IMS - Integrated Management Systems                                           1
Golang Developer                                                              1
Network Automation And QA Intern                                              1
Zoho Developer Intern                                                         1
AI Technology                                                                 1
Product Testing                                                               1
SFDC Tester                                                                   1
XML Developer                                                                 1
Full Stack Development Intern                                                 1
SAP CPI                                                                       1
NET Development                                                               1
Product Analysis                                                              1
Frontend Developer                                                            1
Jira Admin                                                                    1
System Administrator                                                          1
Java Developer Or SQL Database Management Or Frontend Angular Js Expert       1
Software Implementation Specialist                                            1
VB.Net Developer                                                              1
Salesforce Devops                                                             1
Computer Technician/Support Specialist                                        1
Shopify Developer                                                             1
Node.js Development                                                           1
Software Testing Internship/ Training                                         1
Software Developer / Engineer                                                 1
Name: count, dtype: int64